---

- name: Include overrides specific to Centos 7.
  include_tasks: "{{ ansible_distribution }}-{{ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == "7"


- name: Include overrides specific to Debian 9.
  include_tasks: "{{ ansible_distribution }}-{{ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == "9"
