---
- name: update-grub
  command: /usr/sbin/update-grub
  become: 'yes'
  listen: "update-grub"
  # skip for docker ct as there's no point in running
  # update-grub in there
  when: ansible_virtualization_type != "docker"
