---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    box: "${MOLECULE_DISTRO:-debian/stretch64}"
    groups:
      - grub
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      grub:
        user: qwe
        username: qwe
        GRUB_CMDLINE_LINUX_DEFAULT: "quiet"
  lint:
    name: ansible-lint
scenario:
  name: vagrant_libvirt
verifier:
  name: testinfra
  lint:
    name: flake8
